baseURL: "https://samsepro.github.io"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination: 
   pagerSize: 10 
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: AP
      name: Projets
      title: Projets
      url: /AP
      weight: 1
    - identifier: Veille
      name: Veille
      title: Veille
      url: /veille
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Bonjour, je m'appelle"
    title: "Samsidine TOURE."
    subtitle: "Etudiant en BTS SIO option SISR"
    content: "Passionné des métiers de la Tech, j'ai décidé de suivre les Solutions d'Infrastructures Systèmes et Réseaux."
    image: /images/samse.JPG 
    bottomImage:
      enable: true
 

  # About
  about:
    enable: true
    title: "A propos de moi"
    image: "/images/samse.JPG"
    content: |-
      Je suis étudiant en deuxième année BTS SIO mention SISR(Solutions d'Infrastructures Système et Réseaux) au lycée Edme Bouchardon à Chaumont. 
     

    skills:
      enable: true
      title: "Voici quelques technologies acquises lors de ma formation:"
      items:
        - "Active Directory"
        - "Python"
        - "Infrastructures Réseaux"
        - "Windows server"
        - "Linux"
        - "Gestion de projet"
        - "Virtualisation"
        - "CCNA1 & CCNA2" 
        - "Cybersécurité"
        - "Mise en place de serveur Windows AD"
        - "Mise en place de Proxmox"
        - "Déploiement de machines par le réseau"
        - "Supervision réseau avec Zabbix"
        - "Mise en place d'un pare-feu Stormshield"
        - "Mise en place de fonctionnalités DNS, DHCP"
        
        

  # Experience
  experience:
    enable: true
    title: "Expériences Professionnelles"
    items:
    
      - job: "Administrateur Systèmes et Réseaux"
        company: "Createch Informatique"
        date: "Janvier 2025 - Fevrier 2025"
        content: |
          - Mise en place d’un tunnel VPN Client-to-site avec OpenVPN 
          - Configuration et gestion des serveurs Windows et Linux.
          - Assistance à la mise en place d’une infrastructure réseau sécurisée et analyse des logs pour détecter des anomalies.
          - Mise en place de solutions de sauvegarde et de sécurité pour les données sensibles.
          - Mise en place Zabbix, GLPI et OCS Inventory dans l'ESXi avec alertes Discord et un proxy avec SquidGuard sous pfSense.
          - Mise en place IDS / IPS dans l’infrastructure de l’entreprise.
      - job: "Technicien IT"
        company: "SecurInfor Jeux Paris 2024"
        date: "Juillet 2024- sept 2024"
        content: |
          - Support  technique de niveau 2 aux utilisateurs des jeux de PARIS2024
          - Déploiement de PC CIS Paris 2024
          - Installation et la configuration de PC, imprimantes et serveurs pour assurer une infrastructure robuste

      - job: "Technicien IT"
        company: "LLC Consulting"
        date: "mai 2024 - juin 2024"
        content: |
          - Audit et renforcement de la sécurité via l'analyse de vulnérabiltés avec WPScan.
          - Identification et correction de failles de sécurité d'un site Wordpress
          - Développement de scripts Python pour analytics Web
         

     

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "BTS SIO option SISR"
        school:
          name: "lycée Edme Bouchardon"
          url: "https://g.co/kgs/Z8PxANe"
        date: "2023 - 2025"
        GPA: ""
        content:
      - title: "Licence Développement Web, Mobile et Multimédia"
        school:
          name: "Université Cheikh Anta Diop de Dakar, Sénégal"
          url: "https://g.co/kgs/iizoBfS"
        date: "2021 - 2022"
        GPA: ""
        content: |-
    
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://g.co/kgs/CrEA2WN"
      - title: "Baccalauréat"
        school:
          name: "Lycée Taiba ICS de Mboro,Sénégal."
          url: "https://g.co/kgs/YHVFn57"
        GPA: "mention Assez-Bien"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: true
    title: "Certifications"
    items:
      - title: Cisco
        content: Certification Cisco.
        url: https://www.netacad.com/fr/
        image: /images/cisco.png
      - title: Mooc de l'ANSSI
        content: Certification Mooc de l'ANSSI
        url : https://secnumacademie.gouv.fr/
        image : /images/mooc.png
  

  #Contact
  contact:
    enable: true
    title: Contact
    content: Ma boîte mail est toujours ouverte. Que vous ayez une question ou que vous souhaitiez simplement me dire bonjour, je ferai de mon mieux pour vous répondre !
    email: sam.toure@outlook.fr
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: 
      linkedin: https://www.linkedin.com/in/samsidine-tour%C3%A9-1b2a6a284
      twitter:
      instagram: 
      facebook: 

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: false
      content: "minute de lecture"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Lire"
    toc: "Sommaire"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
